application: teamdash-1309
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
