application: vendasta-team-dashboard
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: .*
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
